with prod as (
    select 
    cast(lower(titulo) as varchar(256)) as videojuego,
    cast(features_handheld as boolean) as features_handheld,
    cast(max_players as integer) as jugadores_max,
    cast(multiplatform as boolean) as multiplatform, 
    cast(online as boolean) as online,
    cast(lower(genre) as varchar(256)) as genero,
    cast(licensed as boolean) as licensed,
    cast(lower(publishers) as varchar(256)) as publishers,
    cast(sequel as boolean) as sequel,
    cast(replace(review_score,',','.') as decimal(38,2)) as critica,
    cast(replace(sales,',','.') as decimal(38,2)) as sales, 
    cast(replace(used_price,',','.') as decimal(38,2)) as precio_lanzamiento,
    cast(lower(console) as varchar(256)) as consola,
    cast(rating as varchar(4)) as rating, 
    cast(re_release as boolean) as re_release,
    cast(release_year as integer) as release_year,
    cast(replace(average,',','.') as decimal(38,2)) as average,
    cast(replace(leisure,',','.') as decimal(38,2)) as leisure,
    cast(replace(play_median,',','.') as decimal(38,2)) as play_median,
    cast(replace(polled,',','.') as integer) as polled,
    cast(replace(rushed,',','.') as decimal(38,2)) as rushed,
    cast(replace(comp_average,',','.') as decimal(38,2)) as comp_average,
    cast(replace(comp_leisure,',','.') as decimal(38,2)) as comp_leisure,
    cast(replace(comp_median,',','.') as decimal(38,2)) as comp_median,
    cast(replace(comp_polled,',','.') as integer) as comp_polled,
    cast(replace(comp_rushed,',','.') as decimal(38,2)) as comp_rushed,
    cast(replace(extras_av,',','.') as decimal(38,2)) as extras_av,
    cast(replace(extras_leisure,',','.') as decimal(38,2)) as extras_leisure,
    cast(replace(extras_median,',','.') as decimal(38,2)) as extras_median,
    cast(replace(extras_polled,',','.') as integer) as extras_polled,
    cast(replace(extras_rushed,',','.') as decimal(38,2)) as extras_rushed,
    cast(replace(story_av,',','.') as decimal(38,2)) as story_av,
    cast(replace(story_leisure,',','.') as decimal(38,2)) as story_leisure,
    cast(replace(story_median,',','.') as decimal(38,2)) as story_median,
    cast(replace(story_polled,',','.') as integer) as story_polled,
    cast(replace(story_rushed,',','.') as decimal(38,2)) as story_rushed,
    
    from {{source('trabajo_final','producto')}}
)

select 
    videojuego,
    features_handheld,
    jugadores_max,
    multiplatform, 
    online,
    genero,
    licensed,
    publishers,
    sequel,
    critica,
    sales, 
    precio_lanzamiento,
    consola,
    rating, 
    re_release,
    release_year,
    average,
    leisure,
    play_median,
    polled,
    rushed,
    comp_average,
    comp_leisure,
    comp_median,
    comp_polled,
    comp_rushed,
    extras_av,
    extras_leisure,
    extras_median,
    extras_polled,
    extras_rushed,
    story_av,
    story_leisure,
    story_median,
    story_polled,
    story_rushed
from prod 
order by videojuego